name: Daily Contribution Agent

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate Random Commits
        run: |
          python scripts/update.py
          python scripts/update.py

      - name: Commit and Push
        run: |
          git config --global user.name "adityarao1234"
          git config --global user.email "adityarao1925@gmail.com"

          git add .

          git commit -m "Automated activity update $(date)" || echo "No changes"

          git push